### ISSUE TITLE
hair.json appearing as eye colour in tables

### ISSUE THREAD

**Issue by simulacrum-1** [Cpt-Igloo/ogre-kingdom-wfrp4e#1]
You have hitched on to wfrp's /char system to add Ogres and copied the old RNHD hair.json with eye colour as the name that was fixed in the last update. Hence two eye colour tables appearing.
<img width="726" alt="Screenshot 2021-04-03 at 18 26 32" src="https://user-images.githubusercontent.com/68729767/113520218-7cb18900-9589-11eb-8aba-4db3d915ee2c.png">

**Comment by Cpt-Igloo** [comment]
Thanks! should be fixed now
